### ISSUE TITLE
Error when bundling

### ISSUE THREAD

**Issue by aSegatto** [ashleydavis/ts-project-bundle#1]
I get this error. Compilation and setup are ok from what i can say . I have one microservice and one lib and it's building and running correctly .

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at TsBundler.<anonymous> (/xxxx/node_modules/ts-project-bundle/build/index.js:187:45)
    at step (/xxxx/node_modules/ts-project-bundle/build/index.js:33:23)
    at Object.next (/xxxx/node_modules/ts-project-bundle/build/index.js:14:53)
    at fulfilled (/xxxx/node_modules/ts-project-bundle/build/index.js:5:58) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by ashleydavis** [comment]
If you can provide an example that demonstrates the issue I'll be happy to help you debug it.

**Comment by FredrikBorgstrom** [comment]
It seems like this package doesn't support extended tsconfig files yet (please correct me if I'm wrong), so you need to make sure that all tsconfig.json files has the **"outDir": "path-to-your-output-dir"** set.
